<a href="https://colab.research.google.com/github/tanishaaraoo/Awesome_Robotics_Club_B-Tanisha-Rao-230278/blob/main/Part%20B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import cv2
import numpy as np

def convert_image_to_grid_array(image_path, grid_rows, grid_cols):
    # Load the image
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

    # Apply binary thresholding to make the image black and white
    _, thresholded = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY_INV)

    # Calculate the size of each cell
    cell_height, cell_width = image.shape[0] // grid_rows, image.shape[1] // grid_cols

    # Initialize the grid array
    grid_array = np.zeros((grid_rows, grid_cols), dtype=int)

    # Analyze each cell
    for row in range(grid_rows):
        for col in range(grid_cols):
            # Determine the start and end points of the cell
            start_y, start_x = row * cell_height, col * cell_width
            end_y, end_x = start_y + cell_height, start_x + cell_width

            # Extract the cell using slicing
            cell = thresholded[start_y:end_y, start_x:end_x]

            # Determine if the cell is predominantly black (obstacle)
            if np.count_nonzero(cell) > (cell_height * cell_width) // 2:
                grid_array[row, col] = 1  # Mark as obstacle

    return grid_array

# Path to your grid image
image_path = '/content/photo.jpeg'
grid_rows, grid_cols = 5, 5  # Adjust based on your grid's dimension

# Convert the image to a grid array
grid_array = convert_image_to_grid_array(image_path, grid_rows, grid_cols)

print(grid_array)
#import cv2
import numpy as np
from queue import Queue

def bfs(grid, start, goal):
    directions = [(0, -1), (1, 0), (0, 1), (-1, 0)]  # Movement directions: up, down, left, right
    visited = set([start])
    queue = Queue()
    queue.put((start, [start]))  # Store current position and path so far

    while not queue.empty():
        current, path = queue.get()
        if current == goal:
            # Adjust path to be 1-based before returning
            return [(x+1, y+1) for (x, y) in path]

        for dx, dy in directions:
            next_pos = (current[0] + dx, current[1] + dy)
            if (0 <= next_pos[0] < grid.shape[0] and
                0 <= next_pos[1] < grid.shape[1] and
                grid[next_pos[1], next_pos[0]] == 0 and  # Corrected grid indexing
                next_pos not in visited):

                visited.add(next_pos)
                queue.put((next_pos, path + [next_pos]))

    return None  # If no path found

# Assuming 'grid' is defined
# Adjust 'start' and 'goal' to be 0-based for Python indexing
adjusted_start = (0, 0)  # Adjust for Python's 0-based indexing
adjusted_goal = (4, 4)  # Adjust for Python's 0-based indexing

# Call BFS with adjusted start and goal
path = bfs(grid_array, adjusted_start, adjusted_goal)
print("Binary grid representation (0: free, 1: obstacle):")
print(grid_array)
if path:
    print("Shortest path from start to goal (1-based indexing):", path)
else:
    print("No path found.")

[[0 1 0 0 1]
 [0 1 1 0 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 1 0]]
Binary grid representation (0: free, 1: obstacle):
[[0 1 0 0 1]
 [0 1 1 0 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 1 0]]
Shortest path from start to goal (1-based indexing): [(1, 1), (1, 2), (1, 3), (2, 3), (3, 3), (4, 3), (5, 3), (5, 4), (5, 5)]
